export const ActivePools = [
  {
    id: 1,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 1,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "67079007.22/87083333.33 SLM",
    percentage: "90.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
  },
  {
    id: 2,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 1,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 3,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 4,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 5,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 6,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 7,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 8,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 9,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 10,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 10",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 11,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 11",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 12,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 12",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Active",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  //   {
  //     id: 1,
  //     tag: "upcoming",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
  //   {
  //     id: 2,
  //     tag: "upcoming",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
  //   {
  //     id: 3,
  //     tag: "upcoming",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
  //   {
  //     id: 1,
  //     tag: "completed",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
  //   {
  //     id: 2,
  //     tag: "completed",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
  //   {
  //     id: 3,
  //     tag: "completed",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
  //   {
  //     id: 4,
  //     tag: "completed",
  //     logo: "Logo",
  //     tags: ["1st Phase", "41% complete"],
  //     projectTitle: "Project 12",
  //     projectDescription:
  //       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
  //     minAllocation: "$10",
  //     maxAllocation: "$10",
  //     access: "Public",
  //     totalRaised: "100234.45 USDT",
  //      chain:4002,
  //     status: "Filled",
  //     dateOfCompletion: "23rd Oct, 2022",
  //     SLMAmount: "87079007.22/87083333.33 SLM",
  //     percentage: "100.00%",
  //     tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
  //     tokenPrice: "1 BUSD = 166.66 SLM",
  //     tokenName: "SoliMax",
  //     tokenSymbol: "SLM",
  //     tokenDecimal: "18",
  //     tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
  //     tokenTotalSupply: "1,000,000,000",
  //     aboutProject:
  //       "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
  //     projectBenefits: ["1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.", "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM"],
  //     projectName: "MENZY ECOSYSTEM"
  //   },
];

export const UpcomingPools = [
  {
    id: 1,
    tag: "upcoming",
    logo: "Logo",
    tags: ["TBA"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87077007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 2,
    tag: "upcoming",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 3,
    tag: "upcoming",
    logo: "Logo",
    tags: ["TBA"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 4,
    tag: "upcoming",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 5,
    tag: "upcoming",
    logo: "Logo",
    tags: ["TBA"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 6,
    tag: "upcoming",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
];

export const CompletedPools = [
  {
    id: 1,
    tag: "completed",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 3",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    totalRate: "$100234.45",
    maxAllocation: "$2500",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 2,
    tag: "completed",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 3",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    totalRate: "$100234.45",
    maxAllocation: "$2500",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87089007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
  {
    id: 3,
    tag: "completed",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 3",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    totalRate: "$100234.45",
    maxAllocation: "$2500",
    access: "Public",
    totalRaised: "100234.45 USDT",
    chain: 4002,
    status: "Filled",
    dateOfCompletion: "23rd Oct, 2022",
    currentBalance: 87079007.22,
    targetBalance: 87083333.33,
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
    tokenDistribution: "24th Dec, 2022 (UTC + 1:00)",
    tokenPrice: "1 BUSD = 166.66 SLM",
    tokenName: "SoliMax",
    tokenSymbol: "SLM",
    tokenDecimal: "18",
    tokenAddress: "0xb1957BDbA889686EbdE631DF970ecE6A7571A1B6",
    tokenTotalSupply: "1,000,000,000",
    aboutProject:
      "Menzy is a passive move-to-earn project with additional features such as compete to earn and activity classification based on machine vision. These segments each contain reward mechanisms that grant users MNZ tokens once activated as per the segmentation classes as well as the sub categories. With Menzy’s Move2Earn; you can earn passively by just walking, running and participating in other real world sports and activities. This enables a whole new paradigm for wallets where a wallet can keep increasing total assets over time while still being used for all other utilities: ",
    projectBenefits: [
      "1) Showcase your skills and earn income in the form of MNZ Tokens by competing with other holders in different real world physical sports, games and activities. Menzy uses its AI based computer vision software that acts as a referee to assess your performance.",
      "2) Ensure a healthy living by targeting your daily step count goals on the Menzy application and getting rewarded with MNZ tokens and unique digital assets for maintaining a healthy lifestyle.MENZY ECOSYSTEM",
    ],
    projectName: "MENZY ECOSYSTEM",
  },
];
