export const ActivePools = [
  {
    id: 1,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 2,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 3,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 4,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 5,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 6,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 7,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 8,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 9,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 1",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 10,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 10",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 11,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 11",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
  {
    id: 12,
    tag: "active",
    logo: "Logo",
    tags: ["1st Phase", "41% complete"],
    projectTitle: "Project 12",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$10",
    access: "Public",
  },
];

export const UpcomingPools = [
  {
    id: 1,
    tag: "upcoming",
    logo: "Logo",
    tags: ["TBA"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
  },
  {
    id: 2,
    tag: "upcoming",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
  },
  {
    id: 3,
    tag: "upcoming",
    logo: "Logo",
    tags: ["TBA"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
  },
  {
    id: 4,
    tag: "upcoming",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
  },
  {
    id: 5,
    tag: "upcoming",
    logo: "Logo",
    tags: ["TBA"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
  },
  {
    id: 6,
    tag: "upcoming",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 2",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    minAllocation: "$10",
    maxAllocation: "$200",
    access: "Public",
  },
];

export const CompletedPools = [
  {
    id: 1,
    tag: "completed",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 3",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    totalRate: "$100234.45",
    maxAllocation: "$2500",
    access: "Public",
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
  },
  {
    id: 2,
    tag: "completed",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 3",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    totalRate: "$100234.45",
    maxAllocation: "$2500",
    access: "Public",
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
  },
  {
    id: 3,
    tag: "completed",
    logo: "Logo",
    tags: ["23/11/2023"],
    projectTitle: "Project 3",
    projectDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim",
    totalRate: "$100234.45",
    maxAllocation: "$2500",
    access: "Public",
    SLMAmount: "87079007.22/87083333.33 SLM",
    percentage: "100.00%",
  },
];
